apiVersion: v1
kind: Pod
metadata:
  name: __APP__-app
  namespace: k8squest
  labels:
    app: frontend  # Wrong! Service bu pod ni shu label bilan topolmaydi
    tier: __TIER__
spec:
  containers:
  - name: app
    image: hashicorp/http-echo:latest
    args:
      - "-text=Hello from __APP__!"
    ports:
    - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: __APP__-service
  namespace: k8squest
spec:
  selector:
    app: __APP__
    tier: __TIER__
  ports:
  - port: 80
    targetPort: 5678
